site_name: Manual do Usuário - PEPVagas
docs_dir: conteudo 
site_dir: site 

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: green   
      accent: indigo
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo Noturno

nav:
  - Início: index.md
  - Candidato: candidato.md
  - Empresa: empresa.md
  - Representante: representante.md
  - Profissional Liberal: profissional-liberal.md
  - Membro de Equipe: membro-de-equipe.md
  - Administrador: administrador.md
